services:
  - type: web
    name: hdri-stitcher
    runtime: python
    rootDir: scripts
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
